// Code generated by protoc-gen-go.
// source: meshbuilder.proto
// DO NOT EDIT!

/*
Package meshbuilder is a generated protocol buffer package.

It is generated from these files:
	meshbuilder.proto

It has these top-level messages:
	CreateProjectRequest
	CreateProjectResponse
	AddRequest
	AddResponse
	RetrieveRequest
	RetrieveResponse
	Depth
	Row
*/
package meshbuilder

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateProjectRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateProjectRequest) Reset()                    { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()               {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateProjectResponse struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateProjectResponse) Reset()                    { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()               {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateProjectResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AddRequest struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Depth *Depth `protobuf:"bytes,2,opt,name=depth" json:"depth,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddRequest) GetDepth() *Depth {
	if m != nil {
		return m.Depth
	}
	return nil
}

type AddResponse struct {
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RetrieveRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *RetrieveRequest) Reset()                    { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string            { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()               {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RetrieveRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RetrieveResponse struct {
}

func (m *RetrieveResponse) Reset()                    { *m = RetrieveResponse{} }
func (m *RetrieveResponse) String() string            { return proto.CompactTextString(m) }
func (*RetrieveResponse) ProtoMessage()               {}
func (*RetrieveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Depth struct {
	Rows []*Row `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
	// FOV in degrees
	XFov float32 `protobuf:"fixed32,2,opt,name=x_fov,json=xFov" json:"x_fov,omitempty"`
	YFov float32 `protobuf:"fixed32,3,opt,name=y_fov,json=yFov" json:"y_fov,omitempty"`
}

func (m *Depth) Reset()                    { *m = Depth{} }
func (m *Depth) String() string            { return proto.CompactTextString(m) }
func (*Depth) ProtoMessage()               {}
func (*Depth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Depth) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *Depth) GetXFov() float32 {
	if m != nil {
		return m.XFov
	}
	return 0
}

func (m *Depth) GetYFov() float32 {
	if m != nil {
		return m.YFov
	}
	return 0
}

type Row struct {
	Values []int32 `protobuf:"varint,1,rep,packed,name=values" json:"values,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Row) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateProjectRequest)(nil), "CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "CreateProjectResponse")
	proto.RegisterType((*AddRequest)(nil), "AddRequest")
	proto.RegisterType((*AddResponse)(nil), "AddResponse")
	proto.RegisterType((*RetrieveRequest)(nil), "RetrieveRequest")
	proto.RegisterType((*RetrieveResponse)(nil), "RetrieveResponse")
	proto.RegisterType((*Depth)(nil), "Depth")
	proto.RegisterType((*Row)(nil), "Row")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MeshBuilder service

type MeshBuilderClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
}

type meshBuilderClient struct {
	cc *grpc.ClientConn
}

func NewMeshBuilderClient(cc *grpc.ClientConn) MeshBuilderClient {
	return &meshBuilderClient{cc}
}

func (c *meshBuilderClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := grpc.Invoke(ctx, "/MeshBuilder/CreateProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshBuilderClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := grpc.Invoke(ctx, "/MeshBuilder/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshBuilderClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	out := new(RetrieveResponse)
	err := grpc.Invoke(ctx, "/MeshBuilder/Retrieve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MeshBuilder service

type MeshBuilderServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
}

func RegisterMeshBuilderServer(s *grpc.Server, srv MeshBuilderServer) {
	s.RegisterService(&_MeshBuilder_serviceDesc, srv)
}

func _MeshBuilder_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshBuilderServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MeshBuilder/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshBuilderServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshBuilder_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshBuilderServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MeshBuilder/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshBuilderServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshBuilder_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshBuilderServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MeshBuilder/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshBuilderServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MeshBuilder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MeshBuilder",
	HandlerType: (*MeshBuilderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _MeshBuilder_CreateProject_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _MeshBuilder_Add_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _MeshBuilder_Retrieve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meshbuilder.proto",
}

func init() { proto.RegisterFile("meshbuilder.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4e, 0x32, 0x31,
	0x14, 0x86, 0x99, 0x3f, 0xf2, 0x7d, 0x67, 0x44, 0xe1, 0x28, 0x64, 0x42, 0x34, 0xc1, 0x6e, 0x24,
	0x2e, 0x9a, 0x88, 0x3b, 0x57, 0xa2, 0x86, 0x8d, 0x31, 0x31, 0xbd, 0x01, 0x03, 0xf6, 0x18, 0xc6,
	0x00, 0xc5, 0xb6, 0xcc, 0xc0, 0x0d, 0x79, 0x9d, 0x86, 0x0e, 0x04, 0x1d, 0x71, 0x37, 0xe7, 0x9d,
	0xf7, 0x3c, 0x69, 0x9f, 0x42, 0x63, 0x4a, 0x66, 0x3c, 0x5a, 0xa4, 0x13, 0x49, 0x9a, 0xcf, 0xb5,
	0xb2, 0x8a, 0x5d, 0xc2, 0xc9, 0xbd, 0xa6, 0xa1, 0xa5, 0x67, 0xad, 0xde, 0xe9, 0xd5, 0x0a, 0xfa,
	0x58, 0x90, 0xb1, 0x88, 0x10, 0xce, 0x86, 0x53, 0x4a, 0xbc, 0x8e, 0xd7, 0xfd, 0x2f, 0xdc, 0x37,
	0xbb, 0x80, 0x66, 0xa9, 0x6b, 0xe6, 0x6a, 0x66, 0x08, 0x0f, 0xc1, 0x4f, 0xa5, 0xab, 0x46, 0xc2,
	0x4f, 0x25, 0xbb, 0x01, 0xe8, 0x4b, 0xb9, 0x45, 0x95, 0xfe, 0xe2, 0x29, 0x44, 0x92, 0xe6, 0x76,
	0x9c, 0xf8, 0x1d, 0xaf, 0x1b, 0xf7, 0xaa, 0xfc, 0x61, 0x3d, 0x89, 0x22, 0x64, 0x35, 0x88, 0xdd,
	0x6e, 0x81, 0x66, 0xe7, 0x70, 0x24, 0xc8, 0xea, 0x94, 0x32, 0xfa, 0x83, 0xc7, 0x10, 0xea, 0xbb,
	0xca, 0x66, 0xed, 0x11, 0x22, 0x47, 0xc5, 0x04, 0x42, 0xad, 0x72, 0x93, 0x78, 0x9d, 0xa0, 0x1b,
	0xf7, 0x42, 0x2e, 0x54, 0x2e, 0x5c, 0x82, 0xc7, 0x10, 0x2d, 0x5f, 0xde, 0x54, 0xe6, 0x8e, 0xe1,
	0x8b, 0x70, 0x39, 0x50, 0xd9, 0x3a, 0x5c, 0xb9, 0x30, 0x28, 0xc2, 0xd5, 0x40, 0x65, 0xec, 0x0c,
	0x02, 0xa1, 0x72, 0x6c, 0x41, 0x35, 0x1b, 0x4e, 0x16, 0x54, 0xc0, 0x22, 0xb1, 0x99, 0x7a, 0x9f,
	0x1e, 0xc4, 0x4f, 0x64, 0xc6, 0x77, 0x85, 0x58, 0xbc, 0x85, 0xda, 0x0f, 0x4d, 0xd8, 0xe4, 0xfb,
	0x14, 0xb7, 0x5b, 0x7c, 0xaf, 0x4d, 0x56, 0x41, 0x06, 0x41, 0x5f, 0x4a, 0x8c, 0xf9, 0xce, 0x62,
	0xfb, 0x80, 0x7f, 0xd7, 0x52, 0xc1, 0x2b, 0xf8, 0xb7, 0xbd, 0x35, 0xd6, 0x79, 0xc9, 0x51, 0xbb,
	0xc1, 0x7f, 0x29, 0xa9, 0x8c, 0xaa, 0xee, 0xc9, 0xaf, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0xdc, 0xbc, 0x14, 0x07, 0x02, 0x00, 0x00,
}
