# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshbuilder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meshbuilder.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11meshbuilder.proto\"$\n\x14\x43reateProjectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x15\x43reateProjectResponse\"1\n\nAddRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x05\x64\x65pth\x18\x02 \x01(\x0b\x32\x06.Depth\"\r\n\x0b\x41\x64\x64Response\"\x1f\n\x0fRetrieveRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"*\n\x10RetrieveResponse\x12\x16\n\x06points\x18\x01 \x03(\x0b\x32\x06.Point\"(\n\x05Point\x12\t\n\x01X\x18\x01 \x01(\x02\x12\t\n\x01Y\x18\x02 \x01(\x02\x12\t\n\x01Z\x18\x03 \x01(\x02\"9\n\x05\x44\x65pth\x12\x12\n\x04rows\x18\x01 \x03(\x0b\x32\x04.Row\x12\r\n\x05x_fov\x18\x02 \x01(\x02\x12\r\n\x05y_fov\x18\x03 \x01(\x02\"\x15\n\x03Row\x12\x0e\n\x06values\x18\x01 \x03(\x05\x32\xa6\x01\n\x0bMeshBuilder\x12@\n\rCreateProject\x12\x15.CreateProjectRequest\x1a\x16.CreateProjectResponse\"\x00\x12\"\n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponse\"\x00\x12\x31\n\x08Retrieve\x12\x10.RetrieveRequest\x1a\x11.RetrieveResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CREATEPROJECTREQUEST = _descriptor.Descriptor(
  name='CreateProjectRequest',
  full_name='CreateProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CreateProjectRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=57,
)


_CREATEPROJECTRESPONSE = _descriptor.Descriptor(
  name='CreateProjectResponse',
  full_name='CreateProjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=82,
)


_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='AddRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='depth', full_name='AddRequest.depth', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=133,
)


_ADDRESPONSE = _descriptor.Descriptor(
  name='AddResponse',
  full_name='AddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=148,
)


_RETRIEVEREQUEST = _descriptor.Descriptor(
  name='RetrieveRequest',
  full_name='RetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RetrieveRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=181,
)


_RETRIEVERESPONSE = _descriptor.Descriptor(
  name='RetrieveResponse',
  full_name='RetrieveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='RetrieveResponse.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=225,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='Point.X', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Y', full_name='Point.Y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z', full_name='Point.Z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=267,
)


_DEPTH = _descriptor.Descriptor(
  name='Depth',
  full_name='Depth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='Depth.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_fov', full_name='Depth.x_fov', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_fov', full_name='Depth.y_fov', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=326,
)


_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='Row.values', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=349,
)

_ADDREQUEST.fields_by_name['depth'].message_type = _DEPTH
_RETRIEVERESPONSE.fields_by_name['points'].message_type = _POINT
_DEPTH.fields_by_name['rows'].message_type = _ROW
DESCRIPTOR.message_types_by_name['CreateProjectRequest'] = _CREATEPROJECTREQUEST
DESCRIPTOR.message_types_by_name['CreateProjectResponse'] = _CREATEPROJECTRESPONSE
DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddResponse'] = _ADDRESPONSE
DESCRIPTOR.message_types_by_name['RetrieveRequest'] = _RETRIEVEREQUEST
DESCRIPTOR.message_types_by_name['RetrieveResponse'] = _RETRIEVERESPONSE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Depth'] = _DEPTH
DESCRIPTOR.message_types_by_name['Row'] = _ROW

CreateProjectRequest = _reflection.GeneratedProtocolMessageType('CreateProjectRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEPROJECTREQUEST,
  __module__ = 'meshbuilder_pb2'
  # @@protoc_insertion_point(class_scope:CreateProjectRequest)
  ))
_sym_db.RegisterMessage(CreateProjectRequest)

CreateProjectResponse = _reflection.GeneratedProtocolMessageType('CreateProjectResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEPROJECTRESPONSE,
  __module__ = 'meshbuilder_pb2'
  # @@protoc_insertion_point(class_scope:CreateProjectResponse)
  ))
_sym_db.RegisterMessage(CreateProjectResponse)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDREQUEST,
  __module__ = 'meshbuilder_pb2'
  # @@protoc_insertion_point(class_scope:AddRequest)
  ))
_sym_db.RegisterMessage(AddRequest)

AddResponse = _reflection.GeneratedProtocolMessageType('AddResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESPONSE,
  __module__ = 'meshbuilder_pb2'
  # @@protoc_insertion_point(class_scope:AddResponse)
  ))
_sym_db.RegisterMessage(AddResponse)

RetrieveRequest = _reflection.GeneratedProtocolMessageType('RetrieveRequest', (_message.Message,), dict(
  DESCRIPTOR = _RETRIEVEREQUEST,
  __module__ = 'meshbuilder_pb2'
  # @@protoc_insertion_point(class_scope:RetrieveRequest)
  ))
_sym_db.RegisterMessage(RetrieveRequest)

RetrieveResponse = _reflection.GeneratedProtocolMessageType('RetrieveResponse', (_message.Message,), dict(
  DESCRIPTOR = _RETRIEVERESPONSE,
  __module__ = 'meshbuilder_pb2'
  # @@protoc_insertion_point(class_scope:RetrieveResponse)
  ))
_sym_db.RegisterMessage(RetrieveResponse)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'meshbuilder_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  ))
_sym_db.RegisterMessage(Point)

Depth = _reflection.GeneratedProtocolMessageType('Depth', (_message.Message,), dict(
  DESCRIPTOR = _DEPTH,
  __module__ = 'meshbuilder_pb2'
  # @@protoc_insertion_point(class_scope:Depth)
  ))
_sym_db.RegisterMessage(Depth)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
  DESCRIPTOR = _ROW,
  __module__ = 'meshbuilder_pb2'
  # @@protoc_insertion_point(class_scope:Row)
  ))
_sym_db.RegisterMessage(Row)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class MeshBuilderStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.CreateProject = channel.unary_unary(
          '/MeshBuilder/CreateProject',
          request_serializer=CreateProjectRequest.SerializeToString,
          response_deserializer=CreateProjectResponse.FromString,
          )
      self.Add = channel.unary_unary(
          '/MeshBuilder/Add',
          request_serializer=AddRequest.SerializeToString,
          response_deserializer=AddResponse.FromString,
          )
      self.Retrieve = channel.unary_unary(
          '/MeshBuilder/Retrieve',
          request_serializer=RetrieveRequest.SerializeToString,
          response_deserializer=RetrieveResponse.FromString,
          )


  class MeshBuilderServicer(object):

    def CreateProject(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_MeshBuilderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateProject': grpc.unary_unary_rpc_method_handler(
            servicer.CreateProject,
            request_deserializer=CreateProjectRequest.FromString,
            response_serializer=CreateProjectResponse.SerializeToString,
        ),
        'Add': grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=AddRequest.FromString,
            response_serializer=AddResponse.SerializeToString,
        ),
        'Retrieve': grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=RetrieveRequest.FromString,
            response_serializer=RetrieveResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'MeshBuilder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaMeshBuilderServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def CreateProject(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Add(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Retrieve(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaMeshBuilderStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def CreateProject(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    CreateProject.future = None
    def Add(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Add.future = None
    def Retrieve(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Retrieve.future = None


  def beta_create_MeshBuilder_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('MeshBuilder', 'Add'): AddRequest.FromString,
      ('MeshBuilder', 'CreateProject'): CreateProjectRequest.FromString,
      ('MeshBuilder', 'Retrieve'): RetrieveRequest.FromString,
    }
    response_serializers = {
      ('MeshBuilder', 'Add'): AddResponse.SerializeToString,
      ('MeshBuilder', 'CreateProject'): CreateProjectResponse.SerializeToString,
      ('MeshBuilder', 'Retrieve'): RetrieveResponse.SerializeToString,
    }
    method_implementations = {
      ('MeshBuilder', 'Add'): face_utilities.unary_unary_inline(servicer.Add),
      ('MeshBuilder', 'CreateProject'): face_utilities.unary_unary_inline(servicer.CreateProject),
      ('MeshBuilder', 'Retrieve'): face_utilities.unary_unary_inline(servicer.Retrieve),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_MeshBuilder_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('MeshBuilder', 'Add'): AddRequest.SerializeToString,
      ('MeshBuilder', 'CreateProject'): CreateProjectRequest.SerializeToString,
      ('MeshBuilder', 'Retrieve'): RetrieveRequest.SerializeToString,
    }
    response_deserializers = {
      ('MeshBuilder', 'Add'): AddResponse.FromString,
      ('MeshBuilder', 'CreateProject'): CreateProjectResponse.FromString,
      ('MeshBuilder', 'Retrieve'): RetrieveResponse.FromString,
    }
    cardinalities = {
      'Add': cardinality.Cardinality.UNARY_UNARY,
      'CreateProject': cardinality.Cardinality.UNARY_UNARY,
      'Retrieve': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'MeshBuilder', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
