# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import meshbuilder_pb2 as meshbuilder__pb2


class MeshBuilderStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateProject = channel.unary_unary(
        '/MeshBuilder/CreateProject',
        request_serializer=meshbuilder__pb2.CreateProjectRequest.SerializeToString,
        response_deserializer=meshbuilder__pb2.CreateProjectResponse.FromString,
        )
    self.Add = channel.unary_unary(
        '/MeshBuilder/Add',
        request_serializer=meshbuilder__pb2.AddRequest.SerializeToString,
        response_deserializer=meshbuilder__pb2.AddResponse.FromString,
        )
    self.Retrieve = channel.unary_unary(
        '/MeshBuilder/Retrieve',
        request_serializer=meshbuilder__pb2.RetrieveRequest.SerializeToString,
        response_deserializer=meshbuilder__pb2.RetrieveResponse.FromString,
        )


class MeshBuilderServicer(object):

  def CreateProject(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Add(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Retrieve(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MeshBuilderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateProject': grpc.unary_unary_rpc_method_handler(
          servicer.CreateProject,
          request_deserializer=meshbuilder__pb2.CreateProjectRequest.FromString,
          response_serializer=meshbuilder__pb2.CreateProjectResponse.SerializeToString,
      ),
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=meshbuilder__pb2.AddRequest.FromString,
          response_serializer=meshbuilder__pb2.AddResponse.SerializeToString,
      ),
      'Retrieve': grpc.unary_unary_rpc_method_handler(
          servicer.Retrieve,
          request_deserializer=meshbuilder__pb2.RetrieveRequest.FromString,
          response_serializer=meshbuilder__pb2.RetrieveResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MeshBuilder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
